services:
  postgres:
    image: 'postgres'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped
    networks:
      - shopsphere-net

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password

networks:
  shopsphere-net:
    driver: bridge

volumes:
  postgres:
  mongodb: