name: Server CI Orchestrator

on:
  push:
    branches:
      - 'main'
    paths:
      - 'server/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'server/**'

jobs:
  setup-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup workflows
        run: ./setup-workflows/sh

      - name: Check Copied Workflows
        run: |
          if [ ! -f .github/workflows/auth-service-ci.yaml ]; then
            echo "Workflow file not found. Exiting."
            exit 1
          fi

  auth-service:
    needs: setup-workflows
    uses: ./.github/workflows/auth-service-ci.yaml
    with:
      service-name: auth-service
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
